service: authorization-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    dotenvVars: ${file(configs.js)}
  serverless-offline:
    httpPort: 8000

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer
    events:
      #
