service: import-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment:
    BUCKET: ${self:custom.dotenvVars.BUCKET, env:BUCKET, ''}

  iamRoleStatements:
    - Effect: 'Allow'
      Action: 's3:ListBucket'
      Resource:
        - 'arn:aws:s3:::aws-import-service-catalog'
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        - 'arn:aws:s3:::aws-import-service-catalog/*'

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    dotenvVars: ${file(configs.js)}
  serverless-offline:
    httpPort: 8000

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          cors: true
          method: get
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: aws-import-service-catalog
          event: s3:ObjectCreated:*
          existing: true
